[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildContext = "backend"

[deploy]
startCommand = "scripts/start/app.sh"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
